      - name: Build APK
        run: |
          # Android SDK licenses တွေကို အလိုအလျောက် လက်ခံခိုင်းခြင်း
          yes | sdkmanager --licenses || true
          # Buildozer နဲ့ APK ထုတ်ခြင်း
          buildozer -v android debug
